### ISSUE TITLE
Add feature to create new sections and add users in one step

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/canvas-course-manager#33]
Add a new feature that combines the two "Add multiple new sections to course through CSV" and "Add multiple users to course sections through CSV" features into one feature.  It should take a CSV of group names, group ID prefixes, and user IDs.

**Comment by pushyamig** [comment]
@lsloan When this repo was created it for Unizin Hack-a-thon and we had a use case of creating section/adding users to sections via Canvas SIS process. We had an intern coming who did the UX work for new CCM and here are the wireframes from that https://github.com/tl-its-umich-edu/UX-Work/tree/master/ccm/wireframes. Here is the Google Drive folder for [that](https://drive.google.com/drive/u/0/folders/1jFM54JYJVnOhUTQbZNeGQl5yW7F_uVwl)

**Comment by lsloan** [comment]
Moved to tl-its-umich-edu/canvas_course_manager#292.
